swagger: "2.0"
info:
  title: "Promotion Management Services"
  description: "Promotion management services for Simple and Buy Get promotions"
  version: "1.0.0"
  

tags:
- name: ""
  description: ""
  externalDocs:
    description: ""
    url: "http://someURL"

#######################################################################################
#                      Host , Basepath , Schemes , Content Types                                                     #
#######################################################################################
host: "localhost"

basePath: "/inf/bnkng/evnt/arrnfmntorigevnt/consumr/wrkflwevntmaint/v1"

schemes:
- "https"
- "http"

produces:
    - application/json

consumes:
    - application/json

#######################################################################################
#                      Security                                                       #
#######################################################################################
securityDefinitions:
    API Key:
        type: basic
        description: consumer should present api key and secret as part of standard http authorization header 
        
security:
    - API Key: []

#######################################################################################
#                      Parameters                                                     #
#######################################################################################
parameters:
    x-messageId:
        name: x-messageId
        in: header
        description: Unique message identifier
        type: string
        required: true
    x-appCorelationId:
        name: x-appCorelationId
        in: header
        description: Used to trace a request
        type: string
        required: true
    x-organizationId:
        name: x-organizationId
        in: header
        description: consumers organization
        type: string
        required: true    
        enum:
            - ABC
            - XYZ
    x-originatingSystemId:
        name: x-originatingSystemId
        in: header
        description: System Id of application
        type: string
        required: true
    x-consumerType:
        name: x-consumerType
        in: header
        description: something
        type: string
        required: true
        enum:
            - Everyone
            - Other
    x-userId:
        name: x-userId
        in: header
        description: user invoking API
        type: string
        required: false
    x-userIdScheme:
        name: x-userIdScheme
        in: header
        description: user scheme invoking API
        type: string
        required: false
        enum:
            - EmpId
            - CustomerId
    x-authorization:
        name: x-authorization
        in: header
        description: user auth
        type: string
        required: false        
    x-originatingBSB:
        name: x-originatingBSB
        in: header
        description: BSB
        type: string
        required: false
    x-originatingDeviceId:
        name: x-originatingDeviceId
        in: header
        description: originatingDeviceId
        type: string
        required: false    
    brandSilo:
        name: brandSilo
        in: query
        description: channel identification
        type: string
        required: true
        enum:
            - POODLE
            - MANGY
    applicationId:
        name: applicationId
        in: query
        description: Unique application identifier
        type: string
        required: true    
#######################################################################################
#                      PATHS                                                          #
#######################################################################################
paths:
  /submission/{submissionId}/workActivityTasks:
    post:
      tags:
      - "Create Work Activity"
      summary: "Create Work Activity"
      description: "Create Work Activity"
      operationId: "createWorkActivity"
      parameters:
       - $ref: '#/parameters/x-messageId'
       - $ref: '#/parameters/x-appCorelationId'
       - $ref: '#/parameters/x-organizationId'
       - $ref: '#/parameters/x-originatingSystemId'
       - $ref: '#/parameters/x-consumerType'
       - $ref: '#/parameters/x-authorization'
       - $ref: '#/parameters/brandSilo'
       - $ref: '#/parameters/applicationId'
       - name: submissionId
         in: path
         description: SubmissionId associated with work activity
         type: string
         required: true
       - in: "body"
         name: "WorkActivityRequest"
         description: "Request object that contains payload"
         required: true 
         schema:
           $ref: "#/definitions/WorkActivityRequest"
      
      responses:
        204:
          $ref: "#/responses/204CreateWorkActivitySuccessResponse"
        
        400:
          $ref: "#/responses/400ErrorResponse"
        404:
          $ref: "#/responses/404ErrorResponse"
        500:
          $ref: "#/responses/500ErrorResponse"
  
  /promotion/createSimple:
    post:
      tags:
      - "Create Simple Promotion"
      summary: "Create Simple Promo"
      description: "Create Simple Promo"
      operationId: "createSimplePromo"
      parameters:
       - $ref: '#/parameters/x-messageId'
       - $ref: '#/parameters/x-appCorelationId'
       - $ref: '#/parameters/x-organizationId'
       - $ref: '#/parameters/x-originatingSystemId'
       - $ref: '#/parameters/x-consumerType'
       - $ref: '#/parameters/x-authorization'
       - $ref: '#/parameters/brandSilo'
       - $ref: '#/parameters/applicationId'
       - in: "body"
         name: "SimplePromotionRequest"
         description: "Request object that contains SimplePromo payload"
         required: true 
         schema:
           $ref: "#/definitions/SimplePromoRequest"
      
      responses:
        204:
          $ref: "#/responses/204CreateWorkActivitySuccessResponse"
        
        400:
          $ref: "#/responses/400ErrorResponse"
        404:
          $ref: "#/responses/404ErrorResponse"
        500:
          $ref: "#/responses/500ErrorResponse"
   
  /healthcheck:
    get:
        tags:
            - HealthCheck
        description: heartbeat check of api health
        operationId: getHealthCheckStatus
        responses:
            200:
                $ref: '#/responses/200HealthCheckResponse'
#######################################################################################
#                      Responses                                                      #
#######################################################################################
responses:
    204CreateWorkActivitySuccessResponse:
        description: OK DOK 
                                
    400ErrorResponse:
        description: |
            _Bad Request_
            
            Possible errors
            
            | Error Code | Error Message | Error Description |
            | ---------- | ------------- | ----------------- |
            | 8001       | Invalid input | Parameter missing {0} |
            
        schema:
            type: object
            properties:
                result:
                    type: object
                    properties:
                           errors:
                               type: array
                               items:
                                   $ref: '#/definitions/Error'
                                   
            example:
                result:
                    errors:
                        - code: 1600
                          message: 'Required Header params are missing'
                          details: 'Missing required header param - x-messageId'
    
    404ErrorResponse:
        description: |
            _Resource NOT Found_
            
            Possible errors
            
            | Error Code | Error Message | Error Description |
            | ---------- | ------------- | ----------------- |
            | 8005       | Submission not found | SubmissionId not found in provider system |
            
        schema:
            type: object
            properties:
                result:
                    type: object
                    properties:
                           errors:
                               type: array
                               items:
                                   $ref: '#/definitions/Error'
                                   
            example:
                result:
                    errors:
                        - code: 8005
                          message: 'Submission not found'
                          details: 'SubmissionId not found'
                          
    500ErrorResponse:
        description: |
            _Internal Server Error_
            
            Possible errors
            
            | Error Code | Error Message | Error Description |
            | ---------- | ------------- | ----------------- |
            | 10001       | ISE | Unknown error |
            | 10002       | ISE | Unknown error {0} |
            | 10300       | ISE | Unknown error |
            | 10301       | ISE | Unknown error |
            | 10302       | ISE | Unknown error |
            
        schema:
            type: object
            properties:
                result:
                    type: object
                    properties:
                           errors:
                               type: array
                               items:
                                   $ref: '#/definitions/Error'
                                   
            example:
                result:
                    errors:
                        - code: 10001
                          message: 'Internal Server Error'
                          details: 'Unkknown internal Technical error'
    
    200HealthCheckResponse:
        description: Healthcheck status 
        schema:
            $ref: '#/definitions/HealthcheckStatus'
#######################################################################################
#                      Model Definitions                                                     #
#######################################################################################

definitions:
    
    HealthcheckStatus:
        description: healthcheck status
        properties:
            status:
                type: string
                enum:
                    - success
    WorkActivityRequest:
        description: This is an important object  
        type: object
        properties:
            isCompletionNotificationRequired:
                description: do we want to be notified 
                type: boolean
            isAdhocTask:
                description: run time activity 
                type: boolean
            taskType:
                description: type of task
                type: string
                enum:
                    - TASK
            taskStage:
                description: at what stage the task exists 
                type: string
            priority:
                description: task priority 
                type: string
                enum:
                    - HIGH
                    - MEDIUM
                    - LOW
            ownerCategory:
                description: owner of task
                type: string
            taskSummary:
                type: string 
                description: subject line 
            taskDescription:
                type: string
                description: details of task 
    
    SimplePromoRequest:
        description: Simple Promotion payload  
        type: object
        properties:
            isCompletionNotificationRequired:
                description: do we want to be notified 
                type: boolean
            isAdhocTask:
                description: run time activity 
                type: boolean
            taskType:
                description: type of task
                type: string
                enum:
                    - TASK
            taskStage:
                description: at what stage the task exists 
                type: string
            priority:
                description: task priority 
                type: string
                enum:
                    - HIGH
                    - MEDIUM
                    - LOW
            ownerCategory:
                description: owner of task
                type: string
            taskSummary:
                type: string 
                description: subject line 
            taskDescription:
                type: string
                description: details of task 
                
    Error:
        description: This is an important object  
        type: object
        required:
            - code
            - message
        properties:
            code:
                description: Error code
                type: integer
                format: int32
            message:
                description: Error message 
                type: string            
            details:
                description: Detailed information about the error 
                type: string
